
# ADVERTENCIA: ESTA BASE DE DATOS H2 SERA TEMPORAL PARA HACER PRUEBAS RAPIDAS.
# CUANDO SE IMPLEMENTE LA SUBRED PRIVADA CON RDS POSTGRESQL EN AWS SE USARA POSTGREQL.

# Especifica la ubicacion exacta de la BD (H2, en memoria RAM local)
spring.datasource.url=jdbc:h2:mem:sanosdb;INIT=CREATE SCHEMA IF NOT EXISTS integrations_schema
# Schema
spring.jpa.properties.hibernate.default_schema=integrations_schema
# Que Driver usar para hablar con H2
spring.datasource.driverClassName=org.h2.Driver
# Define las credenciales para autenticarse en la BD.
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:}

# Le dice a Hibernate que hable el "dialecto" de H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Crea o actualiza las Tablas de la BD al arrancar la App
spring.jpa.hibernate.ddl-auto=update
# Mostrar consultas SQL que la aplicacion ejecuta
spring.jpa.show-sql=true

# Activar interfaz web para ver las tablas y hacer consultas SQL desde el navegador.
spring.h2.console.enabled=true
# Direccion de la interfaz.
spring.h2.console.path=/h2-console

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# URL del servicio de reportes
sanos.report-service.url=${SANOS_REPORT_SERVICE_URL:http://localhost:8082}