spring.application.name=msvc-matching

spring.main.web-application-type=none

spring.cloud.function.definition=matchingFunction

aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket=${AWS_S3_BUCKET:sanos-media-prod}

sanos.eventbridge.bus-name=${EVENTBRIDGE_BUS_NAME:sanos-events}
matching.dynamodb.table-name=${DYNAMODB_TABLE:sanos-analytics}
matching.score.threshold=${MATCHING_SCORE_THRESHOLD:70}
matching.distance.km.max=${MATCHING_DISTANCE_KM_MAX:5}
matching.rekognition.threshold=${MATCHING_REKOGNITION_THRESHOLD:80}

logging.level.root=INFO
logging.level.com.javadiseno.sanosysalvos=INFO
