
# ADVERTENCIA: ESTA BASE DE DATOS H2 SERA TEMPORAL PARA HACER PRUEBAS RAPIDAS.
# CUANDO SE IMPLEMENTE LA SUBRED PRIVADA CON RDS POSTGRESQL EN AWS SE USARA POSTGREQL.

# Especifica la ubicación exacta de la BD (H2, en memoria ram de la pc)
spring.datasource.url=jdbc:h2:mem:sanosdb
# Schema
spring.jpa.properties.hibernate.default_schema=reports_schema
# Que Driver usar para hablar con H2
spring.datasource.driverClassName=org.h2.Driver
# Define las credenciales para autenticarse en la BD.
spring.datasource.username=admin
spring.datasource.password=sanos123

# Le dice a Hibernate que hable el "Dialecto" de H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Crea o actualiza las Tablas de la BD al arrancar la App
spring.jpa.hibernate.ddl-auto=update
# Mostrar consultas SQL que la aplicación ejecuta
spring.jpa.show-sql=true

# Activar interfaz web para ver las tablas y hacer consultas SQL desde el navegador.
spring.h2.console.enabled=true
# Dirección de la interfaz.
spring.h2.console.path=/h2-console
