FROM maven:3.9-eclipse-temurin-21-alpine AS build
WORKDIR /w
COPY . .
RUN mvn -q -pl msvc-report -am package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /w/msvc-report/target/msvc-report-*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java","-jar","/app/app.jar"]
