spring.application.name=msvc-analytics

# Lambda no levanta servidor HTTP
spring.main.web-application-type=none

# Spring Cloud Function
spring.cloud.function.definition=analyticsEventHandler;analyticsQueryHandler

# AWS
aws.region=${AWS_REGION:us-east-1}

# DynamoDB
analytics.dynamodb.table-name=${DYNAMODB_TABLE:sanos-y-salvos-analytics}
analytics.dynamodb.ttl-days=${DYNAMODB_TTL_DAYS:365}

# Logging
logging.level.root=INFO
logging.level.com.javadiseno.sanosysalvos=INFO