spring.application.name=msvc-pet
server.port=8083

spring.profiles.active=dev

# feign
sanos.user-service.url=http://localhost:8081

# JSON fechas en formato timestamp para que el front pueda entenderlas 
spring.jackson.serialization.write-dates-as-timestamps=false