spring.application.name=msvc-user
server.port=8081

spring.profiles.active=dev

sanos.pet-service.url=${SANOS_PET_SERVICE_URL:http://localhost:8083}
sanos.report-service.url=${SANOS_REPORT_SERVICE_URL:http://localhost:8082}